.travis.yml
README.md

- Make the script for checking the source tarball simpler by removing the `if` test (unless there's a reason I didn't anticipate?).
- Also add `language: c` to please the [validator](http://yaml.travis-ci.org).
- Can just use `cabal install dist/*-*.tar.gz` if there is no source of confusion.

Simplify script for checking tarball + fix validation error

---

README.md

I forgot to supply the cabal file as the script argument
Sorry for the mistake!  One last change to fix the instructions

Fix example `make_travis_yml.hs` command

---

make_travis_yml.hs

Argument order for diff -u was swapped, and it appeared that packages were downgraded
E.g. `base-orphans` from 0.5.2 to 0.5.1:
```diff
--- installplan.txt	2016-02-28 00:55:57.273548425 +0000
+++ /home/travis/.cabsnap/installplan.txt	2016-02-13 02:05:20.000000000 +0000
@@ -1,7 +1,7 @@
In order, the following would be installed:
Cabal-1.22.4.0 (latest: 1.22.7.0) (via: uuagc-cabal-1.0.6.0) (new version)
HUnit-1.3.1.1 (new package)
-base-orphans-0.5.2 (via: semigroupoids-5.0.1 profunctors-5.2 distributive-0.5.0.2) (new package)
+base-orphans-0.5.1 (via: semigroupoids-5.0.1 profunctors-5.2 distributive-0.5.0.2) (new package)
```

Compare old and new install plans in correct order

---

make_travis_yml_2.hs

If `dist/` is deleted but .ghc.environment.* is not, then the repository is in a state that's going to confuse Cabal.
Fixes https://github.com/hvr/multi-ghc-travis/issues/81.

Removing dist/ in a new-build repo requires removing .ghc.environment.*, too.

---

.travis.yml
fixtures/cabal.project.empty-line.travis.yml
fixtures/cabal.project.messy.travis.yml
make_travis_yml_2.hs

Let's mitigate the possibility that we might pick a different install-plan with `--disable-tests --disable-benchmarks`. (I haven't seen this occur in practice yet, but it wouldn't surprise me if this were possible.)

Pass ${TEST} ${BENCH} to `cabal new-haddock`

---

make_travis_yml_2.hs

Seems like I accidentally broke Travis ability to detect failing tests when using --no-cabal-noise, this patch fixes that by propagating non-zero exit codes from shell pipelines.

Fix --no-cabal-noise resulting in Travis incorrectly reporting test success.

---

make-travis-yml.cabal
make_travis_yml_2.hs

Slightly improve portability across versions as suggested in https://github.com/koalaman/shellcheck/issues/1096#issuecomment-359267583.

Port code to ShellCheck 0.4.7.

---

make_travis_yml_2.hs

Simple new command to list the GHC versions supported by make-travis-yml, for forgetful people like me.

List supported GHC versions for make-travis-yml.

---

.travis.yml
fixtures/cabal.project.empty-line.travis.yml
fixtures/cabal.project.messy.travis.yml
make_travis_yml_2.hs

Should fix https://github.com/haskell-servant/servant-auth/pull/86

There's only one .ghc.environment.* file

---

.travis.yml

Without this change, `cabal new-test` fails.

Fix golden test suite to accommodate for changes from 1bfa6728229c9da.

---

.travis.yml
src/MakeTravisYml.hs

Now that haskell/cabal#5516 has been fixed (and was shipped with `cabal-install-2.4.1.0`, see https://github.com/haskell/cabal/issues/5516#issuecomment-446040712), we can remove a hack that was put in place in `haskell-ci` to work around it.

Remove workaround for haskell/cabal#5516

---

.travis.yml
Main.hs
cli/Main.hs
haskell-ci.cabal
src/HaskellCI.hs
src/HaskellCI/Config.hs
src/HaskellCI/Config/Doctest.hs
src/HaskellCI/Config/HLint.hs
src/HaskellCI/Glob.hs
test/Tests.hs

Split out `DoctestConfig`. Ideally, the relevant script parts would be generated only using `DoctestConfig`, and not as a monolith as it's currently.

Refactor 2019-02-10

---

src/HaskellCI.hs
src/HaskellCI/Project.hs

ping @RyanGlScott, resolves #184
this isn't perfect, but you don't need to copy `source-package-repository` manually. Tests are run, but this is `cabal` bug, I guess?
I can reliably work-around https://github.com/haskell/cabal/issues/5586 because script cannot know the names of packages referenced.

SourceRepo

---

.gitattributes

Currently, GitHub classifies `haskell-ci` as a Roff repository:
This stems from the abundance of `collections/cabal.project.*` files with numeric suffixes, which GitHub mistakes as man pages. This PR is a small patch to correct that [using an override](https://github.com/github/linguist/blob/master/README.md#overrides).
**NOTE:** I'm *assuming* the files contained in [`collections/`](https://github.com/haskell-CI/haskell-ci/tree/master/collections) are Haskell source. If they're not, please let me know and I'll mark them as ordinary `Text`, instead of being any particular language.

Fix repository's incorrect language-classification on GitHub.com

---

.travis.yml
cabal.haskell-ci
src/HaskellCI.hs

I attempted to use the `copy-fields` feature the other day only to realize that I have no idea how it is intended to work. This is my attempt at adding documentation for it.

Document copy-fields, and make local-ghc-options always fire

---

src/HaskellCI.hs
src/HaskellCI/Cli.hs

Currently, there's not a simple way to quickly ascertain the `haskell-ci` version. This adds `--version`, which prints out what you would expect.

Add a --version flag

---

.travis.yml
cabal.haskell-ci
fixtures/cabal.project.copy-fields.all.travis.yml
fixtures/cabal.project.copy-fields.none.travis.yml
fixtures/cabal.project.copy-fields.some.travis.yml
fixtures/cabal.project.empty-line.travis.yml
fixtures/cabal.project.messy.travis.yml
src/HaskellCI.hs
src/HaskellCI/Config.hs
src/HaskellCI/Config/ConstraintSet.hs

- Add global --run-tests/--no-run-tests/--run-tests-jobs to specify
when we actually run tests (maybe less then what we build!)
- Add steps configuration to constraint sets:
- tests
- run-tests
- benchmarks
- haddock
- these are only booleans for now, if you need more control, make
another constraint set!
---
cc @RyanGlScott

Fix #182 and #236

---

cabal.haskell-ci

I recently found myself wondering how to use `env` in a `cabal.haskell-ci` file, but couldn't find any examples of how to do so. This patch adds such an example to this repo's `cabal.haskell-ci` file as a demo.

Add env example in cabal.haskell-ci

---

.travis.yml
fixtures/cabal.project.copy-fields.all.travis.yml
fixtures/cabal.project.copy-fields.none.travis.yml
fixtures/cabal.project.copy-fields.some.travis.yml
fixtures/cabal.project.empty-line.travis.yml
fixtures/cabal.project.messy.travis.yml
src/HaskellCI.hs

As far as I can tell, the `--dry` flag does not do anything in the context of `new-freeze`.

Remove unneeded --dry flag from new-freeze invocation

---

cabal.haskell-ci

Add documentation for jobs-selection in cabal.haskell-ci

---

.travis.yml
fixtures/cabal.project.copy-fields.all.travis.yml
fixtures/cabal.project.copy-fields.none.travis.yml
fixtures/cabal.project.copy-fields.some.travis.yml
fixtures/cabal.project.empty-line.travis.yml
fixtures/cabal.project.messy.travis.yml
fixtures/cabal.project.travis-patch.travis.yml
src/HaskellCI/Travis.hs

The new head.hackage upstream is at https://ghc.gitlab.haskell.org/head.hackage. This updates
`haskell-ci` accordingly, using the stanza found at https://ghc.gitlab.haskell.org/head.hackage/.

Update head.hackage repository stanza to new upstream

---

.travis.yml
fixtures/cabal.project.copy-fields.all.travis.yml
fixtures/cabal.project.copy-fields.none.travis.yml
fixtures/cabal.project.copy-fields.some.travis.yml
fixtures/cabal.project.empty-line.travis.yml
fixtures/cabal.project.messy.travis.yml
fixtures/cabal.project.travis-patch.travis.yml
haskell-ci.cabal
src/HaskellCI/Travis.hs

Due to haskell/cabal#6214, the scripts that `haskell-ci` generates are susceptible to breaking when running `v2-haddock` on `build-type: Custom` packages with certain versions of GHC (e.g., GHC 7.10.3). A fairly simple workaround is to just pass `--with-haddock <path-to-haddock>`, which this patch accomplishes.

Work around haskell/cabal#6214

---

README.md

GHC 8.8.1 was released almost two months ago. It is supported by the HEAD version of this library, but not yet by the Hackage version. In `README.md` please remove the "pre-release" tag from GHC 8.8.1, and then upload a new version to Hackage. Thanks.

GHC 8.8.1 has been released

---

haskell-ci.cabal
src/HaskellCI/Compiler.hs
src/HaskellCI/Travis.hs
src/HaskellCI/Travis/Yaml.hs

Which allows to install GHCJS stuff using `apt` already.
Also bionic works now.

apt sources accept sourcelines now

---

cabal-parsers/cabal-parsers.cabal
cabal-parsers/src/Cabal/Config.hs
cabal-parsers/src/Cabal/Internal/Newtypes.hs

The module is now quite bare minimum,
enough to provide info to find 01-index.tar files
and the storedir.
On my machine
```haskell
*Cabal.Config> readConfig 
Config {cfgRepositories = fromList [("hackage.haskell.org",Repo {repoURL = http://hackage.haskell.org/})], cfgRemoteRepoCache = Identity "/home/ogre/.cabal/packages", cfgInstallDir = Identity "/home/ogre/.cabal/bin", cfgStoreDir = Identity "/home/ogre/.cabal/store"}
```

Add Cabal.Config module

---

cabal-install-parsers/Changelog.md
cabal-install-parsers/cabal-install-parsers.cabal
cabal-install-parsers/fixtures/haskell-ci.golden
cabal-install-parsers/fixtures/haskell-ci.project
cabal-install-parsers/src/Cabal/Project.hs
cabal-install-parsers/test/Golden.hs
fixtures/cabal.project.copy-fields.all.travis.yml
haskell-ci.cabal
src/HaskellCI/Travis.hs

This changes the semantics of `Project`'s `prjOtherFields` (previously `prjOrigFields`) to reflect its intended purpose of being a catch-all field for everything that is not already covered by an existing field of `Project`. I've tweaked golden test in `cabal-parsers-golden` to ensure that these semantics are being upheld by `parseProject`.
Fixes #367.

Rename prjOrigFields to prjOtherFields, change parseProject's semantics

---

.travis.yml
fixtures/cabal.project.copy-fields.all.travis.yml
fixtures/cabal.project.copy-fields.none.travis.yml
fixtures/cabal.project.copy-fields.some.travis.yml
fixtures/cabal.project.empty-line.travis.yml
fixtures/cabal.project.messy.travis.yml
fixtures/cabal.project.travis-patch.travis.yml
haskell-ci.cabal
src/HaskellCI/Config.hs
src/HaskellCI/Travis.hs

Fixes https://github.com/haskell-CI/haskell-ci/issues/275
template-haskell-2.16 added liftTyped,
so now this good to add.

Add -Werror=missing-methods to local packages

---

cabal-install-parsers/Changelog.md
cabal-install-parsers/cabal-install-parsers.cabal
cabal-install-parsers/src/Cabal/Config.hs
cabal-install-parsers/src/Cabal/Package.hs
cabal-install-parsers/src/Cabal/Parse.hs
cabal-install-parsers/src/Cabal/Project.hs
cabal.project
haskell-ci.cabal
src/HaskellCI/Config/Dump.hs
src/HaskellCI/OptparseGrammar.hs
src/HaskellCI/ParsecUtils.hs

As far as I can tell, there are only two changes in `Cabal-3.2.*`                              
that matter to `cabal-install-parsers`/`haskell-ci`:                                           
* The type of `runParseResult` has changed:                                                    
```diff                                                                                      
-runParseResult :: ParseResult a -> ([PWarning], Either (Maybe Version, [PError])        a)  
+runParseResult :: ParseResult a -> ([PWarning], Either (Maybe Version, NonEmpty PError) a)  
```                                                                                          
Currently, various code paths invoke `runParseResult` and store the returned `[PError]` in the `peErrors` field of `ParseError`. To …

Require building with Cabal-3.2.* 

---

cabal.haskell-ci

It was referred to as `install-dependencies-step`, not `install-dependencies` (the actual name), in the comments.

Correct name of install-dependencies option in cabal.haskell-ci

---

haskell-ci.cabal
src/HaskellCI/GitHub/Yaml.hs

GitHub Actions: Use sensible `on` default when --branches isn't set

---

.github/workflows/haskell-ci.yml
haskell-ci.sh
src/HaskellCI/Bash.hs
src/HaskellCI/GitHub.hs
src/HaskellCI/Travis.hs

I also added comments to each backend's module that explains why the particular choice of `-j` is used for that module.
Fixes #421.

Consistently use parallelism when building dependencies

---

.github/workflows/haskell-ci.yml
haskell-ci.cabal
src/HaskellCI/GitHub.hs
src/HaskellCI/GitHub/Yaml.hs

The UX for `continue-on-error` is not the greatest, but it's the closest thing we have to `allow-failures` in GitHub Actions.
Fixes #424.

GitHub Actions: support --allow-failures through continue-on-error

---

.github/workflows/haskell-ci.yml
src/HaskellCI/GitHub.hs
src/HaskellCI/GitHub/Yaml.hs

Unfortunately, omitting a property like `continue-on-error` from all `include` entry causes only one job to be run, as observed in https://github.com/haskell-CI/haskell-ci/pull/425#issuecomment-747047769. To work around this, we now enumerate `continue-on-error` in each `include` entry, verbose as it may be.
While I was in town, I renamed the property in each `include` entry from `continue-on-error` to `allow-failure`, as this makes it less likely to confuse with the top-level `continue-on-error` property (a separate thing entirely).

GitHub Actions: Allowed failure cleanup

---

fixtures/messy.github
haskell-ci.cabal
src/HaskellCI/GitHub.hs

The Travis and Bash backends already do this, but the GitHub Actions backend did not due to a small oversight.

GitHub Actions: Install extra packages from --apt

---

.github/workflows/haskell-ci.yml
fixtures/all-versions.github
fixtures/copy-fields-all.github
fixtures/copy-fields-none.github
fixtures/copy-fields-some.github
fixtures/empty-line.github
fixtures/irc-channels.github
fixtures/messy.github
fixtures/psql.github
fixtures/travis-patch.github
haskell-ci.cabal
src/HaskellCI/GitHub.hs
src/HaskellCI/HeadHackage.hs
src/HaskellCI/Travis.hs

This makes the GitHub Actions backend respect the `--head-hackage` flag, much
in the same way that the Travis backend does.
Altered by Oleg Grenrus: added HeadHackage module with shared stanza
---
Rebased and amended #473

GHA backend: Add head.hackage support

---

.github/workflows/haskell-ci.yml
fixtures/all-versions.github
fixtures/copy-fields-all.github
fixtures/copy-fields-none.github
fixtures/copy-fields-some.github
fixtures/empty-line.github
fixtures/irc-channels.github
fixtures/messy.github
fixtures/psql.github
fixtures/travis-patch.github
src/HaskellCI/GitHub.hs

Previously, `ARG_COMPILER=--ghc --with-compiler=/opt/ghc/$GHC_VERSION/bin/ghc` would be generated. However, `HC=/opt/ghc/$GHC_VERSION/bin/ghc` is defined immediately before that line, so we can simplify this to just `ARG_COMPILER=--ghc --with-compiler=$HC`. Indeed, the `bash` backend already does this—see https://github.com/haskell-CI/haskell-ci/blob/4fd29ae752644c886c29fd509507a2a82b9d69f5/src/HaskellCI/Bash/Template.hs#L477.

GHA backend: simplify ARG_COMPILER's definition slightly

---

.github/workflows/haskell-ci.yml
fixtures/empty-line.github
fixtures/empty-line.travis
fixtures/messy.github
fixtures/messy.travis
haskell-ci.cabal
src/HaskellCI/GitHub.hs
src/HaskellCI/Travis.hs

Due to haskell/cabal#7291, attempting to use `haskell-ci` with `head.hackage` currently will result in `cabal v2-update` hanging forever. I have worked around the issue by writing the `allow-newer` information to `cabal.project` rather than `~/.cabal/config`.

Work around haskell/cabal#7291 by writing allow-newer to cabal.project, not ~/.cabal/config

---

.github/workflows/haskell-ci.yml
fixtures/all-versions.github
fixtures/copy-fields-all.github
fixtures/copy-fields-none.github
fixtures/copy-fields-some.github
fixtures/empty-line.github
fixtures/irc-channels.github
fixtures/messy.github
fixtures/psql.github
fixtures/travis-patch.github
haskell-ci.cabal
src/HaskellCI/Bash.hs
src/HaskellCI/Config/Validity.hs
src/HaskellCI/GitHub.hs
src/HaskellCI/Travis.hs

The `checkout` action requires Git 2.18 or later to function properly, so this is only available with Ubuntu 20.04 (Focal) or later.
Fixes #503.

GHA: Support --distribution and --submodules

---

.github/workflows/haskell-ci.yml
fixtures/all-versions.github
fixtures/copy-fields-all.github
fixtures/copy-fields-none.github
fixtures/copy-fields-some.github
fixtures/empty-line.github
fixtures/enabled-jobs.github
fixtures/irc-channels.github
fixtures/messy.github
fixtures/psql.github
fixtures/travis-patch.github
haskell-ci.cabal
src/HaskellCI/GitHub.hs

This is needed to work around a bug that occurs when installing GHC 8.4.4 by way of `ghcup`. See https://gitlab.haskell.org/haskell/ghcup-hs/-/blob/b0522507be6fa991a819aaf22f9a551757380821/README.md#libnuma-required.
Fixes #516.

Install libnuma-dev for ghcup's benefit

---

.github/workflows/haskell-ci.yml
cabal.project
haskell-ci.sh

The latest Hackage versions of these libraries all support GHC 9.0.

Remove uses of allow-newer from cabal.project

---

cabal-install-parsers/src/Cabal/Config.hs

Although 'findConfig' already respects it, 'resolveConfig' will
try to fill in missing values by examining 'getAppUserDataDirectory',
ignoring CABAL_DIR and possibly picking a wrong path for 'cfgStoreDir'.
This causes failures in e.g. cabal-docspec: https://gitlab.haskell.org/haskell/ghcup-hs/-/jobs/770892#L2501
----
It should also be backported to pre-Cabal-3.6, so we can build a `cabal-docspec` that includes it.

Respect CABAL_DIR in 'resolveConfig'

---

src/HaskellCI/Travis.hs

The previous fix for #395 causes ShellCheck to barf and seems to be a typo.
See https://github.com/haskell-CI/haskell-ci/issues/395

Fix a typo in the fix for #395.

---

README.md

bytestring has stopped using haskell-ci a while ago.

Remove bytestring from examples

---

.github/workflows/haskell-ci.yml
haskell-ci.sh
src/HaskellCI/Bash.hs
src/HaskellCI/Config/Doctest.hs
src/HaskellCI/GitHub.hs

The current default doctest version doesn't work with GHC 9.2. The latest version supports all the GHCs we need, so I've updated the default version and everywhere that a doctest constraint is formed.

Bump doctest default & hardcoded versions for GHC 9.2

---

cabal.haskell-ci
src/HaskellCI/Jobs.hs

For example:
```
*INFO* Generating GitHub config for testing for GHC versions: 7.4.2 7.6.3 7.8.4 7.10.3 8.0.2 8.2.2 8.4.4 8.6.5 8.8.4 8.10.4 9.0.1 9.2.1 ghcjs-8.4
*INFO* these            7.4.2 7.6.3 7.8.4 7.10.3 8.0.2 8.2.2 8.4.4 8.6.5 8.8.4 8.10.4 9.0.1 9.2.1 ghcjs-8.4
*INFO* these-lens       7.4.2 7.6.3 7.8.4 7.10.3 8.0.2 8.2.2 8.4.4 8.6.5 8.8.4 8.10.4 9.0.1 9.2.1 ghcjs-8.4
*INFO* these-optics                              8.0.2 8.2.2 8.4.4 8.6.5 8.8.4 8.10.4 9.0.1 9.2.1 ghcjs-8.4
*INFO* semialign        7.4.2 7.6.3 7.8.4 7.10.3 8.0.2 8.2.2 8.4.4 8.6.5 8.8.4 8.10.4 9.0.1 9.2.1 ghcjs-8.4
*INFO* monad-chronicle  7.4.2 7.6.3 7.8.4 7.10.3 8.0.2 8.2.2 8.4.4 8.6.5 8.8.4 8.10.4 9.0.1 9.2.1 ghcjs-8.4
*INFO* these-tests      7.4.2 7.6.3 7.8.4 7.10.3 8.0.2 8.2.2 8.4.4 8.6.5 8.8.4 8.10.4 9.0.1 …
```

Print jobs-selection: any jobs in a table

---

src/HaskellCI/Tools.hs

GHC 9.2 uses GHC2021 as a default language, which includes PolyKinds and breaks compilation/doctests of some mono kinded code.

Pass the default language along with extensions as an argument

---

src/HaskellCI/Config.hs
src/HaskellCI/Config/Ubuntu.hs

Fix help text for --distribution in a future proof way.
Before:
```
--distribution DIST      distribution version (xenial, bionic)
```
After:
```
--distribution DIST      distribution version (xenial, bionic, focal)
```

Fix help text for --distribution in a future proof way

---

fixtures/irc-channels.github
haskell-ci.cabal
src/HaskellCI/GitHub.hs

In the process, update the IRC Ubuntu version to 20.04.
Fixes #608.

Keep the IRC Ubuntu version in sync with the main job's version

---

.github/workflows/haskell-ci.yml
fixtures/all-versions.github
fixtures/copy-fields-all.github
fixtures/copy-fields-none.github
fixtures/copy-fields-some.github
fixtures/empty-line.github
fixtures/enabled-jobs.github
fixtures/irc-channels.github
fixtures/messy.github
fixtures/psql.github
fixtures/travis-patch.github
src/HaskellCI/GitHub.hs

The cache contains built dependencies. When job fails due to compilation error in the project itself, or due to test failure, next one will have to recompile the same dependencies all over again, because they were not cached for failed job.
This commit saves cache unconditionally, using recently introduced GitHub action 'actions/cache/save@v3'.

Save GitHub cache on failure as well

---

cabal-install-parsers/cabal-install-parsers.cabal

Builds fine and all tests pass. The breaking change doesn't seem to affect us.

Allow tree-diff 0.3

---

cabal.haskell-ci

The `apt` flag is accepted on the command line and in the `cabal.haskell-ci` config file, but it is not documented anywhere making it difficult to discover.

Add `apt` field to template `cabal.haskell-ci`

---

.github/workflows/haskell-ci.yml
fixtures/all-versions.github
fixtures/all-versions.travis
fixtures/copy-fields-all.github
fixtures/copy-fields-none.github
fixtures/copy-fields-some.github
fixtures/enabled-jobs.github
fixtures/enabled-jobs.travis
fixtures/irc-channels.github
fixtures/psql.github
fixtures/travis-patch.github
haskell-ci.cabal
src/HaskellCI.hs
src/HaskellCI/Auxiliary.hs
src/HaskellCI/Compiler.hs
src/HaskellCI/GitHub.hs
src/HaskellCI/Travis.hs

Now you can disable `head.hackage` for GHC-alpha/previews and it won't show in the config. For example https://github.com/haskell-hvr/text-short/pull/42

Decouple head.hackage from job failure and GHC-head/alpha/rc status

---

fixtures/all-versions.travis
fixtures/copy-fields-all.travis
fixtures/copy-fields-none.travis
fixtures/copy-fields-some.travis
fixtures/doctest-version.travis
fixtures/doctest.travis
fixtures/empty-line.travis
fixtures/enabled-jobs.travis
fixtures/fail-versions.travis
fixtures/irc-channels.travis
fixtures/messy.travis
fixtures/psql.travis
fixtures/travis-patch.travis
haskell-ci.cabal
src/HaskellCI/Cabal.hs
src/HaskellCI/Config/Initial.hs
src/HaskellCI/Config/Validity.hs
src/HaskellCI/GitHub.hs

Also remove version mapping, Closes #732

Make GHCUP the only installation method for cabal-install

---

.github/workflows/haskell-ci.yml
Makefile
fixtures/all-versions.github
fixtures/copy-fields-all.github
fixtures/copy-fields-none.github
fixtures/copy-fields-some.github
fixtures/doctest-version.github
fixtures/doctest.github
fixtures/empty-line.github
fixtures/enabled-jobs.github
fixtures/fail-versions.github
fixtures/irc-channels.github
fixtures/messy.github
fixtures/psql.github
fixtures/travis-patch.github
haskell-ci.cabal
src/HaskellCI/GitHub.hs

Resolves #769
Note: maybe we could use ubuntu-latest, but OTOH doing an update once in 3-4 years is not a big trouble.

Switch GHA runner to ubuntu-24.04
