- README.md
I found the `make_travis_yml.hs` script in this repository extremely useful but I only learned how to use the script from another satisfied user.  If it's not too much trouble I'd like to contribute some example instructions upstream so that people can learn how to use this script without relying on word of mouth.
> Add instructions for `make_travis_yml.hs` script

- make_travis_yml_2.hs
And also bump ghc-head to 8.3.
> Add ghc-8.2.1 to known GHCs

- make_travis_yml_2.hs
This is useful, as I don't want to build others `master` branches. If I want to build something else, I do a PR.
> Add branch option

- .travis.yml
- make_travis_yml.hs
- make_travis_yml_2.hs
> Build haddocks

- .travis.yml
- make-travis-yml.cabal
- make_travis_yml_2.hs
Makes you regenerate `.travis.yml` with
```
make_travis_yml_2.hs -r .travis.yml
```
> Implement --regenerate

- make_travis_yml_2.hs
> Add a flag to filter out cabal noise from test results.

- make_travis_yml_2.hs
This is more direct copy&paste from `cabal-install`.
> Redo cabal.project parser

- .travis.yml
- cabal.make-travis-yml
- fixtures/cabal.project.empty-line.travis.yml
- fixtures/cabal.project.messy.travis.yml
- make_travis_yml_2.hs
- ghc-options for local packages
- ${BENCH} in new-test invocations (to not change the build-plan)
- toggle of --no-tests --no-benchmarks step (saves time for big
projects)
> Ryan's requests

- .travis.yml
- fixtures/cabal.project.empty-line.travis.yml
- fixtures/cabal.project.messy.travis.yml
- make_travis_yml_2.hs
Don't merge until Ryan verifies it solves the problem.
> Omit local packages in installed constraints

- .travis.yml
- fixtures/cabal.project.empty-line.travis.yml
- fixtures/cabal.project.messy.travis.yml
- make_travis_yml_2.hs
> Use new-sdist

- haskell-ci.cabal
- make_travis_yml_2.hs
> Update to ShellCheck 0.6.0.

- README.md
Does this look more correct, ping @fgaz @RyanGlScott
> Update readme. Resolves #190

- .travis.yml
- fixtures/cabal.project.copy-fields.all.travis.yml
- fixtures/cabal.project.copy-fields.none.travis.yml
- fixtures/cabal.project.copy-fields.some.travis.yml
- fixtures/cabal.project.empty-line.travis.yml
- fixtures/cabal.project.messy.travis.yml
- haskell-ci.cabal
- src/HaskellCI.hs
Fixes #249
@23Skidoo  can you check this; this should work better (`cabal` didn't like `-w ghc-head` at some point)
> Change how HC and HCPKG is calculated

- src/HaskellCI.hs
- src/HaskellCI/Cli.hs
That's unused feature, which is implemented suboptimally.
Let's see how it can be added later.
But for now, I'm removing it completely;
so I don't need to try migrate it.
> Remove collections

- src/HaskellCI.hs
@RyanGlScott does this work for you?
> Try to sort non-cwd regenerate

- .travis.yml
- fixtures/cabal.project.copy-fields.all.travis.yml
- fixtures/cabal.project.copy-fields.none.travis.yml
- fixtures/cabal.project.copy-fields.some.travis.yml
- fixtures/cabal.project.empty-line.travis.yml
- fixtures/cabal.project.messy.travis.yml
- fixtures/cabal.project.travis-patch.travis.yml
- haskell-ci.cabal
- src/HaskellCI/Travis.hs
> Suppress grep -v's non-zero exit codes

- Makefile
- src/HaskellCI/Tools.hs
@RyanGlScott does this fix the #270?
> Don't use alpha for determing 'latest' job

- .travis.yml
- fixtures/cabal.project.copy-fields.all.travis.yml
- fixtures/cabal.project.copy-fields.none.travis.yml
- fixtures/cabal.project.copy-fields.some.travis.yml
- fixtures/cabal.project.empty-line.travis.yml
- fixtures/cabal.project.messy.travis.yml
- fixtures/cabal.project.travis-patch.travis.yml
- haskell-ci.cabal
- src/HaskellCI.hs
- src/HaskellCI/Project.hs
- src/HaskellCI/TestedWith.hs
- src/HaskellCI/Travis.hs
ping @RyanGlScott
After second thought: supporting `optional-packages` may be handy for projects where vendored things come and go.
> Optional packages

- .travis.yml
- src/HaskellCI/Travis.hs
@RyanGlScott can you try with this branch?
> Fix a small bug in 277 implementation

- README.md
This wasn't obvious to me from the README or the command-line options and I had to read the source code to find out :-)
> Explain how to work with multiple local projects

- cabal-parsers/cabal-parsers.cabal
- cabal-parsers/src/Cabal/Config.hs
- cabal-parsers/src/Cabal/Index.hs
- cabal-parsers/test/Index.hs
I think this is last larger feature PR for `cabal-parsers` before its release.
cc @RyanGlScott
> Add Cabal.Index for parse fast metadata from the index

- .travis.yml
- cabal.haskell-ci
- fixtures/cabal.project.copy-fields.all.travis.yml
- fixtures/cabal.project.copy-fields.none.travis.yml
- fixtures/cabal.project.copy-fields.some.travis.yml
- fixtures/cabal.project.empty-line.travis.yml
- fixtures/cabal.project.messy.travis.yml
- fixtures/cabal.project.travis-patch.travis.yml
- src/HaskellCI/Config.hs
- src/HaskellCI/Travis.hs
It used /internal/ marked verbosity.
See https://github.com/haskell/cabal/issues/6383
> Remove coloring of output

- haskell-ci.cabal
- src/HaskellCI.hs
- src/HaskellCI/Config.hs
- src/HaskellCI/Config/ConstraintSet.hs
- src/HaskellCI/Config/Doctest.hs
- src/HaskellCI/Config/HLint.hs
- src/HaskellCI/Prelude.hs
- src/HaskellCI/TestedWith.hs
- src/HaskellCI/Tools.hs
We only need a small part, so let's use small library.
Also we don't need microlens, Cabal have it all.
> Use generic-lens-lite instead of generic-lens

- .hlint.yaml
- haskell-ci.cabal
- src/HaskellCI/Travis.hs
- src/HaskellCI/YamlSyntax.hs
See https://github.com/haskell-CI/haskell-ci/issues/269#issuecomment-586318569
cc @RyanGlScott this should work now, I tried with `tree-diff``
> Try to fix IRC notifications template

- cabal-install-parsers/src/Cabal/Project.hs
- fixtures/cabal.project.copy-fields.all
- fixtures/cabal.project.copy-fields.all.travis.yml
Fixes the bug observed in https://github.com/haskell-CI/haskell-ci/pull/368#issuecomment-613419533.
> Actually filter out source-repository-packages from prjOtherFields

- .travis.yml
- CHANGELOG.md
- haskell-ci.cabal
- src/HaskellCI/Config/Doctest.hs
- src/HaskellCI/Travis.hs
- Fix #395, set HCPKG on macOS to correct value
- Make default doctest version 0.17
> Prepare 0.10.2

- cabal-install-parsers/cabal-install-parsers.cabal
- haskell-ci.cabal
> Allow ansi-terminal 0.11

- haskell-ci.cabal
- src/HaskellCI.hs
- src/HaskellCI/Config.hs
I found myself needing this flag in certain configurations of mine.
> Add --github-patches counterpart to --travis-patches

- .github/workflows/haskell-ci.yml
- fixtures/irc-channels.github
- src/HaskellCI/GitHub.hs
> GHA: Use always() to ensure IRC job is always run

- Makefile
- src/HaskellCI/GitHub.hs
> Fix #440: Accept more urls as github origin

- cabal.haskell-ci
- haskell-ci.cabal
- src/HaskellCI/Config/ConstraintSet.hs
- src/HaskellCI/GitHub.hs
See https://github.com/ekmett/ad/runs/1953010049?check_suite_focus=true#step:27:89 for an example of this in action.
> Allow running cabal-docspec in constraint-sets

- src/HaskellCI/Cli.hs
- src/HaskellCI/Config.hs
- src/HaskellCI/Config/HLint.hs
- src/HaskellCI/OptionsGrammar.hs
- src/HaskellCI/OptparseGrammar.hs
> Fix #487: enable bash-completion for file and directories

- .github/workflows/haskell-ci.yml
- fixtures/all-versions.github
- fixtures/copy-fields-all.github
- fixtures/copy-fields-none.github
- fixtures/copy-fields-some.github
- fixtures/empty-line.github
- fixtures/irc-channels.github
- fixtures/messy.github
- fixtures/psql.github
- fixtures/travis-patch.github
- haskell-ci.cabal
- src/HaskellCI/GitHub.hs
- src/HaskellCI/GitHub/Yaml.hs
I've tested this out on `singletons` [here](https://github.com/goldfirere/singletons/runs/2090801268), and it appears to work as you'd expect.
> GitHub Actions: GHCJS support

- cabal-install-parsers/cabal-install-parsers.cabal
Builds fine and all tests pass here.
> Allow tasty 1.4

- .github/workflows/haskell-ci.yml
- haskell-ci.cabal
- src/HaskellCI/Config/Doctest.hs
- src/HaskellCI/Travis.hs
also bump ShellCheck and attoparsec version ranges
> Doctest 0.18

- cabal-install-parsers/cabal-install-parsers.cabal
- haskell-ci.cabal
- src/HaskellCI/YamlSyntax.hs
Tests pass
----
Also maybe do a revision update on hackage?
> cabal-install-parsers: Allow to build with aeson >=2

- fixtures/all-versions.github
- fixtures/all-versions.travis
- fixtures/enabled-jobs.github
- fixtures/enabled-jobs.travis
- haskell-ci.cabal
- src/HaskellCI/HeadHackage.hs
> head.hackage with ghc >=9.3

- src/HaskellCI/GitHub.hs
I tested this out [here](https://github.com/RyanGlScott/gha-sandbox/runs/4055973201?check_suite_focus=true#step:17:22), and it does what you'd expect.
Fixes #551.
> GHA: Respect the `jobs` option

- cabal-install-parsers/Changelog.md
- cabal-install-parsers/cabal-install-parsers.cabal
- cabal-install-parsers/src/Cabal/Internal/Glob.hs
- cabal-install-parsers/src/Cabal/Project.hs
- cabal.project
- haskell-ci.cabal
This kinds of reverts the #539 patch, but then reapplies a slight modification of it.
> Revert 539

- .github/workflows/haskell-ci.yml
- cabal.haskell-ci
- fixtures/all-versions.github
- fixtures/copy-fields-all.github
- fixtures/copy-fields-none.github
- fixtures/copy-fields-some.github
- fixtures/empty-line.github
- fixtures/enabled-jobs.github
- fixtures/irc-channels.github
- fixtures/messy.github
- fixtures/psql.github
- fixtures/travis-patch.github
- src/HaskellCI/Config.hs
- src/HaskellCI/Config/Ubuntu.hs
- src/HaskellCI/GitHub.hs
Also run ubuntu jobs on 20.04 image
> Add Ubuntu Jammy

- fixtures/all-versions.github
- fixtures/copy-fields-all.github
- fixtures/copy-fields-none.github
- fixtures/copy-fields-some.github
- fixtures/empty-line.github
- fixtures/enabled-jobs.github
- fixtures/irc-channels.github
- fixtures/messy.github
- fixtures/psql.github
- fixtures/travis-patch.github
- src/HaskellCI/GitHub.hs
Bump github/actions to latest: checkout@v3, cache@v3, irc-message-action@v2
I didn't change the  package `version` in `haskell-ci.cabal`.
> Bump github/actions to latest: checkout@v3, cache@v3, irc-message-action@v2

- CHANGELOG.md
- README.md
- haskell-ci.cabal
> Prepare 0.16

- .github/workflows/haskell-ci.yml
- fixtures/all-versions.github
- fixtures/copy-fields-all.github
- fixtures/copy-fields-none.github
- fixtures/copy-fields-some.github
- fixtures/doctest-version.github
- fixtures/doctest.github
- fixtures/empty-line.github
- fixtures/enabled-jobs.github
- fixtures/irc-channels.github
- fixtures/messy.github
- fixtures/psql.github
- fixtures/travis-patch.github
- src/HaskellCI/GitHub.hs
> Use `ghcup-prereleases-0.0.8.yaml`

- fixtures/all-versions.github
- fixtures/all-versions.travis
- fixtures/doctest-version.github
- fixtures/doctest-version.travis
- fixtures/doctest.github
- fixtures/doctest.travis
- fixtures/enabled-jobs.github
- fixtures/enabled-jobs.travis
- haskell-ci.cabal
- src/HaskellCI/HeadHackage.hs
> head.hackage >=9.11

- .github/workflows/haskell-ci.yml
- fixtures/all-versions.github
- fixtures/copy-fields-all.github
- fixtures/copy-fields-none.github
- fixtures/copy-fields-some.github
- fixtures/doctest-version.github
- fixtures/doctest.github
- fixtures/empty-line.github
- fixtures/enabled-jobs.github
- fixtures/fail-versions.github
- fixtures/irc-channels.github
- fixtures/messy.github
- fixtures/psql.github
- fixtures/travis-patch.github
- haskell-ci.cabal
- src/HaskellCI/Config/Grammar.hs
- src/HaskellCI/Config/History.hs
- src/HaskellCI/Config/Initial.hs
- src/HaskellCI/Config/Type.hs
- src/HaskellCI/GitHub.hs
- src/HaskellCI/GitHub/Yaml.hs
- src/HaskellCI/Prelude.hs
- src/HaskellCI/SetupMethod.hs
- test/Tests.hs
> Setup method tests
